all of index pages made responsive
Mirazyzz/ExpenseTracker pull request #81
Opened 2024-11-08 15:53 UTC by Ramadan1011

2024-11-08 16:18 UTC, jamshidbek7375 submitted a review, later dismissed

2024-11-08 19:13 UTC, Boburm1rzo submitted a review, later dismissed

2024-11-09 06:53 UTC, BegzhanMaxamatxanov commented
Nice!

2024-11-09 06:53 UTC, BegzhanMaxamatxanov approved these changes
Good job)

2024-11-09 10:48 UTC, davron41 commented on ExpenseTracker/ExpenseTracker/Views/Shared/_Sidebar.cshtml
> +        }
if (creenWidth < 768 && dockBar.isOpen) {
  // logic
  return;
}

if (!dockBar.isOpen){
  // logic
}

2024-11-09 10:50 UTC, davron41 requested changes
please, perform small code quality improvements.

2024-11-09 11:02 UTC, jamshidbek7375 approved these changes

2024-11-09 11:03 UTC, Boburm1rzo approved these changes
👍

2024-11-09 11:10 UTC, davron41 approved these changes
looks good.

2024-11-09 11:13 UTC, Ramadan1011 commented on ExpenseTracker/ExpenseTracker/Views/Shared/_Sidebar.cshtml
> +        }
fixed

2024-11-09 11:14 UTC, merged