fix-email-templates
Mirazyzz/ExpenseTracker pull request #82
Opened 2024-11-08 16:13 UTC by jamshidbek7375

Before

![image](https://github.com/user-attachments/assets/83ca7e04-dd8f-4f36-8ee4-3982af17f4eb)

After 

![image](https://github.com/user-attachments/assets/e5f13b93-f0dc-4b08-8bb0-d56a3b459aab)

2024-11-08 16:28 UTC, Ramadan1011 requested changes
Discuss my review with others

2024-11-08 16:28 UTC, Ramadan1011 commented on ExpenseTracker/ExpenseTracker.Application/Stores/WalletStore.cs
> +                var message = new EmailMessage(userEmail, "", "Collaboration Invitation", null);
I think _username_ should be given to the second parameter of the **EmailMessage** method

2024-11-08 17:03 UTC, Ramadan1011 approved these changes
Great

2024-11-08 17:03 UTC, Ramadan1011 commented on ExpenseTracker/ExpenseTracker.Application/Stores/WalletStore.cs
> +                var message = new EmailMessage(userEmail, "", "Collaboration Invitation", null);
> > I think _username_ should be given to the second parameter of the **EmailMessage** method
> 
> hali ro'yhatdan o'tmagan kishining qanday qilib UserName ni olamiz

Oops! my mistake, I think that the registered user is being invited

2024-11-08 17:33 UTC, Abdulazim1771 submitted a review, later dismissed

2024-11-08 17:44 UTC, Boburm1rzo commented
In my opinion, instead of email, it would be better to write a username

2024-11-08 19:14 UTC, Boburm1rzo submitted a review, later dismissed

2024-11-08 19:27 UTC, jamshidbek7375 commented
> In my opinion, instead of email, it would be better to write a username

How to write the username of a person who has not yet registered here

2024-11-09 10:44 UTC, davron41 requested changes
Instead of user email let's just say "Hi"

2024-11-09 11:02 UTC, Ramadan1011 approved these changes
great

2024-11-09 11:03 UTC, Boburm1rzo approved these changes
👍

2024-11-09 11:06 UTC, davron41 approved these changes
looks good.

2024-11-09 11:07 UTC, Abdulazim1771 approved these changes

2024-11-09 11:07 UTC, merged